---
- venue: <a href="https://informationplusconference.com/2023">Info+ Conference</a>
  year: 2023
  role: Communication, Design Co-Chair
- venue: <a href="https://altvis.github.io">alt.vis</a>
  year: 2023
  role: Organizing Committee
- venue: <a href="https://altvis.github.io">alt.vis</a>
  year: 2022
  role: Organizing Committee
- venue: <a href="https://eyeofestival.com/">Eyeo Festival</a>
  year: 2022
  role: Student Volunteer
- venue: <a href="https://ieeevis.org/year/2020/welcome">IEEE VIS</a>
  year: 2020
  role: Student Volunteer
- venue: College of Engineering Diversity Committee, U. of Utah
  year: 2020
  role: Grad Representative
- venue: "<a href='https://visionsofthefuture.github.io/'>VISions of the Future: Workshop on Sustainable Practices within Visualization and Physicalisation</a>"
  year: 2024
  role: Organizing Committee
- venue: <a href="https://www.computer.org/digital-library/magazines/cg/critical-data-visualization">CG&A Special Issue on Critical Data Visualization</a>
  year: 2024
  role: Guest Editor
- venue: <a href="https://event.sdu.dk/eurovis">EuroVis</a>
  year: 2024
  role: Student Volunteer
